name: QA Automation Tests

"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar Allure CLI
      run: |
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Instalar dependencias Python
      run: |
        pip install behave selenium webdriver-manager allure-behave

    - name: Correr pruebas
      run: |
        python -m behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results

    - name: Generar reporte Allure
      if: always()
      run: |
        allure generate reports/allure-results --clean -o reports/allure-report

    - name: URL del reporte
      if: always()
      run: |
        echo "🔗 Reporte disponible en: https://dunkandhu.github.io/tecfix-qa"

    - name: Publicar en GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports/allure-report